"""Geo-first source discovery for Russian urban-content collection."""

# ruff: noqa: I001

from .access import (
    DirectorySourcePolicyResolver,
    NetworkRobotsEvaluator,
    RobotsEvaluator,
    SourceAccessAuthorizer,
    SourcePolicyResolver,
    StaticSourcePolicyResolver,
)
from .browser import (
    BrowserRenderError,
    BrowserRenderer,
    PlaywrightBrowserRenderer,
    RenderedComment,
    RenderedPage,
    classify_browser_block,
)
from .classify import SourceClassifier, geo_evidence
from .collection import (
    CandidateCollectionError,
    CandidateCollectionResult,
    CandidateCollector,
    CollectorRouter,
    DiscoveryCollectionStageHandler,
    source_message_document,
)
from .engine import DiscoveryEngine
from .http import StaticHtmlFetcher
from .map_reviews import MapReviewUnavailableCollector
from .models import (
    ACTIVE_SOURCE_KINDS,
    DiscoveryPlan,
    DiscoveryQuery,
    GeoScope,
    SearchHit,
    SourceCandidate,
    SourceKind,
    SourceOutcome,
    SourceReasonCode,
    SourceState,
    canonical_url,
)
from .orchestration import GeoDiscoveryPreparingHandler
from .places import (
    CompositePlaceEnricher,
    OsmPoiEnricher,
    OverpassTransport,
    PlaceApiError,
    PlaceEnricher,
    PlaceEnrichmentResult,
    PlaceRecord,
    StdlibOverpassTransport,
    StdlibTwoGisTransport,
    TwoGisPlacesEnricher,
    TwoGisTransport,
    build_place_enricher_from_env,
)
from .providers import (
    JsonPostTransport,
    SearchProvider,
    SearchProviderError,
    StdlibJsonPostTransport,
    UnavailableSearchProvider,
    YandexSearchProvider,
    parse_yandex_xml,
)
from .public_web import PublicWebCollector, geo_relevance_hint
from .query import GeoQueryBuilder
from .telegram import (
    TelegramCollector,
    TelegramCredentials,
    TelegramGateway,
    TelegramRecord,
    TelegramTarget,
    TelethonTelegramGateway,
    UnavailableTelegramGateway,
    build_telegram_collector_from_env,
    parse_telegram_target,
    telegram_search_terms,
)
from .territory import (
    TerritoryGeolocationEngine,
    TerritoryResolutionError,
    TerritoryResolver,
)

__all__ = [
    "ACTIVE_SOURCE_KINDS",
    "BrowserRenderError",
    "BrowserRenderer",
    "CandidateCollectionError",
    "CandidateCollectionResult",
    "CandidateCollector",
    "CollectorRouter",
    "CompositePlaceEnricher",
    "DirectorySourcePolicyResolver",
    "DiscoveryCollectionStageHandler",
    "DiscoveryEngine",
    "DiscoveryPlan",
    "DiscoveryQuery",
    "GeoDiscoveryPreparingHandler",
    "GeoQueryBuilder",
    "GeoScope",
    "JsonPostTransport",
    "MapReviewUnavailableCollector",
    "NetworkRobotsEvaluator",
    "OsmPoiEnricher",
    "OverpassTransport",
    "PlaceApiError",
    "PlaceEnricher",
    "PlaceEnrichmentResult",
    "PlaceRecord",
    "PlaywrightBrowserRenderer",
    "PublicWebCollector",
    "RenderedComment",
    "RenderedPage",
    "RobotsEvaluator",
    "SearchHit",
    "SearchProvider",
    "SearchProviderError",
    "SourceAccessAuthorizer",
    "SourceCandidate",
    "SourceClassifier",
    "SourceKind",
    "SourceOutcome",
    "SourcePolicyResolver",
    "SourceReasonCode",
    "SourceState",
    "StaticHtmlFetcher",
    "StaticSourcePolicyResolver",
    "StdlibJsonPostTransport",
    "StdlibOverpassTransport",
    "StdlibTwoGisTransport",
    "TelegramCollector",
    "TelegramCredentials",
    "TelegramGateway",
    "TelegramRecord",
    "TelegramTarget",
    "TelethonTelegramGateway",
    "TerritoryGeolocationEngine",
    "TerritoryResolutionError",
    "TerritoryResolver",
    "TwoGisPlacesEnricher",
    "TwoGisTransport",
    "UnavailableSearchProvider",
    "UnavailableTelegramGateway",
    "YandexSearchProvider",
    "build_place_enricher_from_env",
    "build_telegram_collector_from_env",
    "canonical_url",
    "classify_browser_block",
    "geo_evidence",
    "geo_relevance_hint",
    "parse_telegram_target",
    "parse_yandex_xml",
    "source_message_document",
    "telegram_search_terms",
]
