"""Public event and thematic clustering API."""

from .components import (
    ClusterAssignment,
    ClusteringBackend,
    CosineGraphClusterer,
    EmbeddingBackend,
    EmbeddingBatch,
    HashingEmbeddingBackend,
    HDBSCANClusteringBackend,
    IdentityReductionBackend,
    ReductionBackend,
    ReductionBatch,
    SentenceTransformerEmbeddingBackend,
    UMAPReductionBackend,
)
from .models import (
    ALGORITHM_VERSION,
    EVENT_LEVELS,
    SCHEMA_VERSION,
    EventBatchResult,
    EventBatchStats,
    EventCluster,
    EventClusteringConfig,
    EventLevel,
    EventMessage,
    ScopeDiagnostic,
    ScopeStatus,
    canonical_json,
    digest_json,
)
from .orchestration import EventClusteringStageHandler, event_messages_from_previous_outputs
from .runtime import EventClusteringEngine

__all__ = [
    "ALGORITHM_VERSION",
    "EVENT_LEVELS",
    "SCHEMA_VERSION",
    "ClusterAssignment",
    "ClusteringBackend",
    "CosineGraphClusterer",
    "EmbeddingBackend",
    "EmbeddingBatch",
    "EventBatchResult",
    "EventBatchStats",
    "EventCluster",
    "EventClusteringConfig",
    "EventClusteringEngine",
    "EventClusteringStageHandler",
    "EventLevel",
    "EventMessage",
    "HashingEmbeddingBackend",
    "HDBSCANClusteringBackend",
    "IdentityReductionBackend",
    "ReductionBackend",
    "ReductionBatch",
    "ScopeDiagnostic",
    "ScopeStatus",
    "SentenceTransformerEmbeddingBackend",
    "UMAPReductionBackend",
    "canonical_json",
    "digest_json",
    "event_messages_from_previous_outputs",
]
