"Backend parser platform with compliance and security gates."""

from .base import ParserAdapter
from .compliance import ComplianceGate, compliance_snapshot
from .manifest import (
    load_source_policy,
    source_policy_summary,
    validate_source_policy_document,
)
from .models import (
    AccessMethod,
    AuditEvent,
    AuditEventType,
    AuthorIdentifierMode,
    ComplianceContext,
    ComplianceDecision,
    DataCategory,
    DataProtectionPolicy,
    ParserCoverage,
    ParserExecutionError,
    ParserPage,
    ParserPlatformError,
    ParserRequest,
    ParserRunResult,
    ParserRunStatus,
    PermanentParserError,
    PermissionEvidence,
    PermissionEvidenceKind,
    PermissionStatus,
    RateLimitPolicy,
    RequirementDecision,
    RobotsDecision,
    RobotsRequirement,
    SecurityPolicy,
    SourceNotApprovedError,
    SourcePolicy,
    SourcePolicyError,
    SourceRegistrationError,
    SourceResearchRecord,
    TemporaryParserError,
)
from .registry import ParserRegistry
from .runtime import ParserRunner, TokenBucketLimiter
from .security import (
    AuthorPseudonymizer,
    UnsafeOutboundRequestError,
    filter_metadata,
    transform_author_identifier,
    validate_content_type,
    validate_outbound_url,
    validate_response_size,
)
from .store import (
    AuditSink,
    FileParserCheckpointStore,
    InMemoryAuditSink,
    InMemoryParserCheckpointStore,
    JsonlAuditSink,
    ParserCheckpointStore,
    ParserStoreError,
)
from .transport import (
    CredentialProvider,
    LowLevelHttpClient,
    NullCredentialProvider,
    ParserServices,
    SafeHttpTransport,
    TransportRequest,
    TransportResponse,
    UnavailableTransport,
)

__all__ = [
    "AccessMethod",
    "AuditEvent",
    "AuditEventType",
    "AuditSink",
    "AuthorIdentifierMode",
    "AuthorPseudonymizer",
    "ComplianceContext",
    "ComplianceDecision",
    "ComplianceGate",
    "CredentialProvider",
    "DataCategory",
    "DataProtectionPolicy",
    "FileParserCheckpointStore",
    "InMemoryAuditSink",
    "InMemoryParserCheckpointStore",
    "JsonlAuditSink",
    "LowLevelHttpClient",
    "NullCredentialProvider",
    "ParserAdapter",
    "ParserCheckpointStore",
    "ParserCoverage",
    "ParserExecutionError",
    "ParserPage",
    "ParserPlatformError",
    "ParserRegistry",
    "ParserRequest",
    "ParserRunResult",
    "ParserRunStatus",
    "ParserServices",
    "ParserRunner",
    "ParserStoreError",
    "PermanentParserError",
    "PermissionEvidence",
    "PermissionEvidenceKind",
    "PermissionStatus",
    "RateLimitPolicy",
    "RequirementDecision",
    "RobotsDecision",
    "RobotsRequirement",
    "SafeHttpTransport",
    "SecurityPolicy",
    "SourceNotApprovedError",
    "SourcePolicy",
    "SourcePolicyError",
    "SourceResearchRecord",
    "SourceRegistrationError",
    "TemporaryParserError",
    "TokenBucketLimiter",
    "TransportRequest",
    "TransportResponse",
    "UnavailableTransport",
    "UnsafeOutboundRequestError",
    "compliance_snapshot",
    "filter_metadata",
    "load_source_policy",
    "source_policy_summary",
    "transform_author_identifier",
    "validate_content_type",
    "validate_outbound_url",
    "validate_response_size",
    "validate_source_policy_document",
]
