"""Public package of SOIKA UDS Development."""

from .contracts import (
    AnalysisResult,
    CoverageSummary,
    JobStatus,
    MessageClassification,
    ModelResult,
    PrecisionLevel,
    SourceMessage,
    TerritoryContext,
)
from .engine import SoikaEngine
from .integration import (
    CURRENT_CONTRACT_VERSION,
    SUPPORTED_CONTRACT_VERSIONS,
    AnalysisRequestV1,
    AnalysisResultV1,
    ContractIssue,
    ContractValidationError,
    ContractVersion,
    IdempotencyConflictError,
    JobStatusV1,
    MessageType,
    ResultProvenance,
    assert_idempotent_request,
    contract_info,
    export_schema_bundle,
    parse_contract_document,
    schema_bundle_digest,
)
from .orchestration import (
    PIPELINE_STAGES,
    CallableStageHandler,
    CheckpointState,
    ConcurrentUpdateError,
    FileJobStore,
    InMemoryJobStore,
    InvalidStageOutputError,
    JobLeaseError,
    JobNotFoundError,
    JobRecord,
    MissingStageHandlerError,
    OrchestrationError,
    OrchestrationStoreError,
    PermanentStageError,
    PipelineStage,
    RetryableStageError,
    RetryPolicy,
    SoikaOrchestrator,
    StageCheckpoint,
    StageContext,
    StageExecutionError,
    StageResult,
)
from .prediction import Prediction, PredictionFormatError

__version__ = "0.5.0"

__all__ = [
    "CURRENT_CONTRACT_VERSION",
    "PIPELINE_STAGES",
    "SUPPORTED_CONTRACT_VERSIONS",
    "AnalysisRequestV1",
    "AnalysisResult",
    "AnalysisResultV1",
    "CallableStageHandler",
    "CheckpointState",
    "ConcurrentUpdateError",
    "ContractIssue",
    "ContractValidationError",
    "ContractVersion",
    "CoverageSummary",
    "FileJobStore",
    "IdempotencyConflictError",
    "InMemoryJobStore",
    "InvalidStageOutputError",
    "JobLeaseError",
    "JobNotFoundError",
    "JobRecord",
    "JobStatus",
    "JobStatusV1",
    "MessageClassification",
    "MessageType",
    "MissingStageHandlerError",
    "ModelResult",
    "OrchestrationError",
    "OrchestrationStoreError",
    "PermanentStageError",
    "PipelineStage",
    "PrecisionLevel",
    "Prediction",
    "PredictionFormatError",
    "ResultProvenance",
    "RetryPolicy",
    "RetryableStageError",
    "SoikaEngine",
    "SoikaOrchestrator",
    "SourceMessage",
    "StageCheckpoint",
    "StageContext",
    "StageExecutionError",
    "StageResult",
    "TerritoryContext",
    "assert_idempotent_request",
    "contract_info",
    "export_schema_bundle",
    "parse_contract_document",
    "schema_bundle_digest",
    "__version__",
]
